# Font
font_family      family="FiraCode Nerd Font" style="Retina"
bold_font        family="FiraCode Nerd Font" style="Bold"
italic_font      family="FiraCode Nerd Font" style="Italic"
bold_italic_font family="FiraCode Nerd Font" style="Bold Italic"
font_size 10.0

# Cursor
cursor            #58a6ff
cursor_text_color #0d1117
cursor_shape          block
cursor_blink_interval 0
